name: Build and Upload Zip

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn run build

      - name: Zip dist folder
        run: zip -r dist.zip dist

      - name: Upload dist.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: dist.zip
      - name: Upload ZIP to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist.zip
